name: Build i2c-tools

on:
  push:
    branches:
      - master
      - cicd
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 * * 0'
  workflow_dispatch:

jobs:
  build-i2c-tools:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch:
          - armv7l
          - arm
    env:   
      xcompile_vars: 'CC=${{matrix.arch}}-linux-musleabihf-gcc CXX=${{matrix.arch}}-linux-musleabihf-g++ INCLUDE="-I/usr/${{matrix.arch}}-linux-musleabihf/include/"'

    steps:
    - uses: actions/checkout@v2

    - name: Set up cross-compiler
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: coolitsystemsinc/cdu-build
        github_token: ${{ secrets.ACTIONS_AUTH }}        
        workflow: musl-artifact.yaml
        workflow_conclusion: success
        name: ${{matrix.arch}}-linux-musleabihf-cross
        path: .

    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf ${{matrix.arch}}-linux-musleabihf-cross.tgz
        sudo cp -r ./${{matrix.arch}}-linux-musleabihf-cross/* /usr/

    - name: Compile i2c-tools
      run: |
        sudo make ${{ env.xcompile_vars }}
    
    - name: Upload i2c-tools binary
      uses: actions/upload-artifact@v2
      with:
        name: i2c-tools-${{matrix.arch}}
        path: |
          ./tools/
          !./tools/*.*
